import type { WorkflowDefinition } from '../types.js'

export const researchWorkflow: WorkflowDefinition = {
  name: 'research',
  displayName: 'Deep Research',
  description: 'Iterative multi-source research with evidence synthesis and citations.',
  initialPhase: 'scope',
  phases: {
    scope: {
      name: 'scope',
      instruction: [
        'Understand the research goal and clarify boundaries.',
        'Check the code index for existing research on this topic (use CodeIndex).',
        'If prior research exists with high relevance, summarize what is known.',
        'State the research question clearly and confirm scope with the user.',
      ].join('\n'),
      allowedTools: ['Read', 'Glob', 'Grep', 'CodeIndex', 'WebSearch'],
      gate: { type: 'model_done' },
      transitions: ['decompose'],
    },
    decompose: {
      name: 'decompose',
      instruction: [
        'Break the research question into 3-7 specific sub-queries.',
        'For each sub-query, note which search engine is most appropriate:',
        '- arxiv: academic papers (CS, physics, math)',
        '- pubmed: biomedical/health literature',
        '- wikipedia: background/definitions/overviews',
        '- github: code implementations, libraries, frameworks',
        '- duckduckgo/searxng: general web results',
        '',
        'Output a numbered list of sub-queries with recommended engines.',
      ].join('\n'),
      gate: { type: 'model_done' },
      transitions: ['gather'],
    },
    gather: {
      name: 'gather',
      instruction: [
        'For each sub-query from the decompose phase, spawn a researcher agent:',
        '- Set persona to "researcher"',
        '- Include the sub-query and preferred engine in the task',
        '- Use blocking=false for parallel execution',
        'Then collect all results with CollectAgent.',
        '',
        'Each researcher agent will search, fetch promising sources, and return findings.',
      ].join('\n'),
      allowedTools: ['SubAgent', 'CollectAgent', 'WebSearch', 'WebFetch', 'Read'],
      gate: { type: 'model_done' },
      transitions: ['synthesize'],
    },
    synthesize: {
      name: 'synthesize',
      instruction: [
        'Analyze all gathered evidence:',
        '1. Identify corroborating findings across sources',
        '2. Flag contradictions between sources',
        '3. Identify gaps where information is missing',
        '',
        'If critical gaps exist and this is not the 3rd iteration,',
        'generate follow-up queries and transition back to gather.',
        'Otherwise, proceed to report.',
      ].join('\n'),
      allowedTools: ['Read', 'Glob', 'Grep'],
      gate: { type: 'model_done' },
      transitions: ['gather', 'report'],
    },
    report: {
      name: 'report',
      instruction: [
        'Produce two outputs:',
        '',
        '1. INLINE SUMMARY (in your response, max 500 tokens):',
        '## Research: [Topic]',
        '**Key Findings:**',
        '1. [Finding] — [Source](url)',
        '**Gaps/Uncertainties:**',
        '- [What was not found]',
        '**Recommendation:**',
        '[How this applies to the current task]',
        '',
        '2. FULL REPORT (save to .cynco/research/YYYY-MM-DD-<topic-slug>.md):',
        '# Research: [Topic]',
        'Date, Query, Engines used, Iterations',
        '## Summary, ## Findings (by sub-query), ## Sources, ## Gaps',
      ].join('\n'),
      allowedTools: ['Write', 'Read'],
      gate: { type: 'model_done' },
      transitions: ['index', 'done'],
    },
    index: {
      name: 'index',
      instruction: [
        'Index the research report into the project vector store using IndexResearch.',
        'Pass the report file path from the previous phase.',
        'This makes findings discoverable via CodeIndex in future sessions.',
      ].join('\n'),
      allowedTools: ['IndexResearch'],
      gate: { type: 'model_done' },
      transitions: ['done'],
    },
  },
}
